// <auto-generated />
using System;
using Filament.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filament.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FilamentDbContext))]
    partial class FilamentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Filament.Infrastructure.Entities.FilamentTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DefaultNetWeightGrams")
                        .HasColumnType("int");

                    b.Property<int>("EmptySpoolWeightGrams")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Brand", "Material", "Type", "Color");

                    b.ToTable("filament_types", (string)null);
                });

            modelBuilder.Entity("Filament.Infrastructure.Entities.SpoolEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EmptySpoolWeightGramsOverride")
                        .HasColumnType("int");

                    b.Property<string>("FilamentTypeId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InitialNetGrams")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RemainingGrams")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilamentTypeId");

                    b.HasIndex("Status");

                    b.ToTable("spools", (string)null);
                });

            modelBuilder.Entity("Filament.Infrastructure.Entities.SpoolEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeltaGrams")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProjectUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("RemainingAfterGrams")
                        .HasColumnType("int");

                    b.Property<string>("SpoolId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("SpoolId", "OccurredAt");

                    b.ToTable("spool_events", (string)null);
                });

            modelBuilder.Entity("Filament.Infrastructure.Entities.SpoolEntity", b =>
                {
                    b.HasOne("Filament.Infrastructure.Entities.FilamentTypeEntity", "FilamentType")
                        .WithMany("Spools")
                        .HasForeignKey("FilamentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FilamentType");
                });

            modelBuilder.Entity("Filament.Infrastructure.Entities.SpoolEventEntity", b =>
                {
                    b.HasOne("Filament.Infrastructure.Entities.SpoolEntity", "Spool")
                        .WithMany("Events")
                        .HasForeignKey("SpoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spool");
                });

            modelBuilder.Entity("Filament.Infrastructure.Entities.FilamentTypeEntity", b =>
                {
                    b.Navigation("Spools");
                });

            modelBuilder.Entity("Filament.Infrastructure.Entities.SpoolEntity", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
